/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.seanachaidh.handyparking;

public class User {
    private int id;
    private String name, password, email;
    private boolean guide;

    public int getId() {
        return this.id;
    }

    public boolean isGuide() {
        return guide;
    }

    public void setGuide(boolean guide) {
        this.guide = guide;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public User(String name, String password, String email, boolean guide) {
        this.name = name;
        this.password = password;
        this.email = email;
        this.guide = guide;
    }

}
